added input form and impersonate option
AliSzu/ChuckNorrisJokes pull request #2
Opened 2023-06-16 11:05 UTC by AliSzu

2023-06-16 11:10 UTC, rafalhadzicki commented on src/api/jokesApi.ts
> +  fetchRandomJokes: async (params: string): Promise<AxiosResponse<ChuckJoke>|AxiosError> => {
you can put which params you're expecting exactly

2023-06-16 11:13 UTC, rafalhadzicki commented on src/api/jokesApi.ts
> +      const response = await jokesClient.get<ChuckJoke>(`${PATHS.RANDOM_CHUCK_JOKE_PATH}${params}`);
axios client has param supports, you don't need to pass that way. Instead you can use
` await jokesClient.get<ChuckJoke>(PATHS.RANDOM_CHUCK_JOKE_PATH,{
params:{param1, param2,etc}
});`

2023-06-16 11:17 UTC, rafalhadzicki commented on src/components/Image/Image.tsx
> +  const imgClass = customName ? 'imageUnknown' : 'imageChuck'
use enum here

2023-06-16 11:25 UTC, rafalhadzicki commented on src/components/Image/Image.tsx
> +
I don't think you need this useEffect and useState [image, setImage]

2023-06-16 11:27 UTC, rafalhadzicki commented on src/components/Image/Image.tsx
> +import unkownImg from '../../assets/img/unknown.png'
typo 😸 install vscode extension for typo checking https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

2023-06-16 11:31 UTC, rafalhadzicki commented on src/components/MainScreen/MainScreen.tsx
> +  const fetchJokes = async (params: string) => {
change it the same way as I suggested I previous comment

2023-06-16 11:31 UTC, rafalhadzicki commented on src/components/MainScreen/MainScreen.tsx
> +      await fetchJokes("");
params should be optional so you don't have to pass empty strings

2023-06-16 11:33 UTC, rafalhadzicki commented on src/components/MainScreen/MainScreen.tsx
> +    params = customName ? params + `${nameParams}${customName}` : params + "";
once you use axios params you won't need that

2023-06-16 11:34 UTC, rafalhadzicki requested changes

2023-06-16 11:34 UTC, rafalhadzicki commented on src/components/MainScreen/MainScreen.tsx
> +    params = customName ? params + `${nameParams}${customName}` : params + "";
once you use axios params you won't need that

2023-06-16 12:18 UTC, Szulerinio commented on src/components/MainScreen/MainScreen.tsx
> +        <Image customName={customName ? true : false} />
you can use 
```suggestion
        <Image customName={!!customName} />
```

2023-06-16 12:21 UTC, Szulerinio commented on src/components/MainScreen/MainScreen.tsx
> +  const [customName, setCustomName] = useState<string>();
doesn't typescript mark this as error? 
you type this state as string, yet pass no string as default state, and later in onFormSubmit pass 
setCustomName(customName)
where customName has type: 
customName: string | undefined

2023-06-16 12:23 UTC, Szulerinio commented on src/components/AlertSnackbar/AlertSnackbar.tsx
> +  message: string | undefined
this is perfectly ok, but if you don't know, you can use 
```suggestion
  message?: string
  ```

2023-06-20 08:21 UTC, rafalhadzicki commented on src/api/jokesApi.ts
> +      const response = await jokesClient.get<ChuckJoke>(`${PATHS.RANDOM_CHUCK_JOKE_PATH}`, {
don't need `$

2023-06-20 08:28 UTC, rafalhadzicki approved these changes

2023-06-20 08:28 UTC, merged